DROP TABLE IF EXISTS marks;

CREATE TABLE marks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    office TEXT NOT NULL,
    mark INTEGER NOT NULL,
    comment TEXT,
    current_user TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
